### ISSUE TITLE
and* as well as or* are missing

### ISSUE THREAD

**Issue by Gavinok** [carpentry-org/time#3]
I am not sure if `and*` and `or*` where part of a previous version of carp but they are now missing. Replacing them with `and` as well as `or` makes this compile but executing any code leads to a multitude of errors like this one.

```
String String_prn(const String *s) {
                                ^
out/main.c:14969:21: error: passing 'const char **' to parameter of type 'const String *'
      (aka 'char *const *') discards qualifiers in nested pointer types
      [-Werror,-Wincompatible-pointer-types-discards-qualifiers]
  temp = String_prn(&p->tm_zone);
                    ^~~~~~~~~~~
../carp-v0.5.5-x86_64-linux//core/carp_string.h:119:33: note: passing argument to
      parameter 's' here
String String_prn(const String *s) {
```

**Comment by hellerve** [comment]
Which version are you basing this on? There are no references to `and*` or `or*` in the current version.

**Comment by Gavinok** [comment]
Sorry, this was intended for the url library. got mixed up making fixes. I'll move this issue over there.

**Comment by Gavinok** [comment]
Oh ok these are all resolved. this just comes from them being loaded by the http library
